webapps2024/payapp/urls.py
from django.urls import path
from .views import TransactionsView, ApproveTransactionView, DeclineTransactionView

app_name = "payapp"

urlpatterns = [
    path("transactions", TransactionsView.as_view(), name="transactions"),
    path(
        "<int:pk>/approve",
        ApproveTransactionView.as_view(),
        name="approve-transaction",
    ),
    path(
        "<int:pk>/decline",
        DeclineTransactionView.as_view(),
        name="decline-transaction",
    ),
]

webapps2024/register/urls.py
from django.urls import path
from django.contrib.auth import views as dj_auth_views
from .views import (
    CustomLoginView,
    RegisterView,
    DashBoardView,
    AccountsPageView,
)

app_name = "register"

urlpatterns = [
    path("", DashBoardView.as_view(), name="dashboard"),
    path("account", AccountsPageView.as_view(), name="account"),
    path("login", CustomLoginView.as_view(), name="login"),
    path("register", RegisterView.as_view(), name="register"),
    path("logout/", dj_auth_views.LogoutView.as_view(), name="logout"),
]

webapps2024/webapps2024/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("register.urls")),
    path("", include("payapp.urls")),
    path("admin/", admin.site.urls),
]

webapps2024/templates/user/account.html
{% extends './base.html' %}
{% comment %} {% load humanize %} {% endcomment %}

{% load crispy_forms_tags %}

{% block title %}
  <title>Account Details</title>
{% endblock %}

{% block submain %}
  <main class="container">
    {% for message in messages %}
      {% if message.tags %}
        <div class="alert {{ message.tags }}">{{ message }}</div>
      {% else %}
        <div class="alert alert-info">{{ message }}</div>
      {% endif %}
    {% endfor %}
    <h3>Account settings</h3>
    <div class="row py-5 d-flex align-items-center justify-content-evenly">
      <div class="col-6">
        <h4>Profile</h4>
        {% crispy account_form %}
      </div>
      <div class="col-3 my-2">
        <h4>Change password</h4>
        {% crispy password_form %}
      </div>
      <div class="col-9 my-5">
        <h4>Change currency</h4>
        {% crispy currency_form %}
      </div>
    </div>
  </main>
{% endblock %}

webapps2024/templates/user/base.html
{% extends '../base.html' %}
{% load static %}
{% block styles %}
  <style>
    body {
      min-height: 75rem;
      padding-top: 4.5rem;
    }
    
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }
    
    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
    
    .b-example-divider {
      width: 100%;
      height: 3rem;
      background-color: rgba(0, 0, 0, 0.1);
      border: solid rgba(0, 0, 0, 0.15);
      border-width: 1px 0;
      box-shadow: inset 0 0.5em 1.5em rgba(0, 0, 0, 0.1), inset 0 0.125em 0.5em rgba(0, 0, 0, 0.15);
    }
    
    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }
    
    .bi {
      vertical-align: -0.125em;
      fill: currentColor;
    }
    
    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }
    
    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }
    
    .btn-bd-primary {
      --bd-violet-bg: #712cf9;
      --bd-violet-rgb: 112.520718, 44.062154, 249.437846;
    
      --bs-btn-font-weight: 600;
      --bs-btn-color: var(--bs-white);
      --bs-btn-bg: var(--bd-violet-bg);
      --bs-btn-border-color: var(--bd-violet-bg);
      --bs-btn-hover-color: var(--bs-white);
      --bs-btn-hover-bg: #6528e0;
      --bs-btn-hover-border-color: #6528e0;
      --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
      --bs-btn-active-color: var(--bs-btn-hover-color);
      --bs-btn-active-bg: #5a23c8;
      --bs-btn-active-border-color: #5a23c8;
    }
    
    .bd-mode-toggle {
      z-index: 1500;
    }
    
    .bd-mode-toggle .dropdown-menu .active .bi {
      display: block !important;
    }
  </style>

  {% block substyles %}

  {% endblock %}
{% endblock %}

{% block main %}
  <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
      <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z" />
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
      <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z" />
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
      <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z" />
      <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z" />
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
      <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z" />
    </symbol>
  </svg>

  <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button" aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (auto)">
      <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
        <use href="#circle-half"></use>
      </svg>
      <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
      <li>
        <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
          <svg class="bi me-2 opacity-50" width="1em" height="1em">
            <use href="#sun-fill"></use>
          </svg>Light<svg class="bi ms-auto d-none" width="1em" height="1em">
            <use href="#check2"></use>
          </svg>
        </button>
      </li>
      <li>
        <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
          <svg class="bi me-2 opacity-50" width="1em" height="1em">
            <use href="#moon-stars-fill"></use>
          </svg>Dark<svg class="bi ms-auto d-none" width="1em" height="1em">
            <use href="#check2"></use>
          </svg>
        </button>
      </li>
      <li>
        <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
          <svg class="bi me-2 opacity-50" width="1em" height="1em">
            <use href="#circle-half"></use>
          </svg>Auto<svg class="bi ms-auto d-none" width="1em" height="1em">
            <use href="#check2"></use>
          </svg>
        </button>
      </li>
    </ul>
  </div>

  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Paypal</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarCollapse">
        <div>
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              {# prettier-ignore #}
              <a class="nav-link 
              {% if request.path == '/' %}active{% endif %}
              " aria-current="{% if request.path == '' %}page{% endif %}" href="{% url 'register:dashboard' %}">Home</a>
            </li>
            <li class="nav-item">
              {# prettier-ignore #}
              <a class="nav-link {% if request.path == '/transactions' %}active{% endif %}" href="{% url 'payapp:transactions' %}" aria-current="{% if request.path == '/transactions' %}page{% endif %}">Transactions</a>
            </li>
            <li class="nav-item">
              {# prettier-ignore #}
              <a class="nav-link {% if request.path == '/account' %}active{% endif %}" href="{% url 'register:account' %}" aria-current="{% if request.path == '/account' %}page{% endif %}">Account</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-danger" href="{% url 'register:logout' %}">Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>

  {% block submain %}

  {% endblock %}
{% endblock %}

webapps2024/templates/user/dashboard.html
{% extends './base.html' %}
{% load humanize %}
{% load crispy_forms_tags %}
{% load custom_filters %}
{% block title %}
  <title>Account Overview</title>
{% endblock %}

{% block substyles %}
  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }
    
    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
    
    .b-example-divider {
      width: 100%;
      height: 3rem;
      background-color: rgba(0, 0, 0, 0.1);
      border: solid rgba(0, 0, 0, 0.15);
      border-width: 1px 0;
      box-shadow: inset 0 0.5em 1.5em rgba(0, 0, 0, 0.1), inset 0 0.125em 0.5em rgba(0, 0, 0, 0.15);
    }
    
    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }
    
    .bi {
      vertical-align: -0.125em;
      fill: currentColor;
    }
    
    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }
    
    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }
    
    .btn-bd-primary {
      --bd-violet-bg: #712cf9;
      --bd-violet-rgb: 112.520718, 44.062154, 249.437846;
    
      --bs-btn-font-weight: 600;
      --bs-btn-color: var(--bs-white);
      --bs-btn-bg: var(--bd-violet-bg);
      --bs-btn-border-color: var(--bd-violet-bg);
      --bs-btn-hover-color: var(--bs-white);
      --bs-btn-hover-bg: #6528e0;
      --bs-btn-hover-border-color: #6528e0;
      --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
      --bs-btn-active-color: var(--bs-btn-hover-color);
      --bs-btn-active-bg: #5a23c8;
      --bs-btn-active-border-color: #5a23c8;
    }
    
    .bd-mode-toggle {
      z-index: 1500;
    }
    
    .bd-mode-toggle .dropdown-menu .active .bi {
      display: block !important;
    }
    p > span.text-start {
      text-align: start !important;
    }
  </style>
{% endblock %}

{% block submain %}
  <div class="p-5 text-center rounded-3 bg-body-secondary">
    {% for message in messages %}
      {% if message.tags %}
        <div class="alert {{ message.tags }}">{{ message }}</div>
      {% else %}
        <div class="alert alert-info">{{ message }}</div>
      {% endif %}
    {% endfor %}
    <h3>Account overview</h3>
    <div class="container">
      <div class="overview__top">
        <div class="overview__top__top d-flex justify-content-evenly my-5">
          {% comment %}account details{% endcomment %}
          <div class="d-flex flex-column justify-content-center">
            <p>Balance</p>
            <p class="fw-bold">
              {% if account_type == 'usd' %}
                $
              {% else %}
                ₤
              {% endif %}{{ balance|to_value:request.user|floatformat:2|intcomma }}
            </p>
          </div>
          <div class="text-start">
            <p>
              <span class="text-start">Account number:&nbsp;</span>{{ account_number }}
            </p>
            <p>
              <span class="text-start">Account username:&nbsp;</span>@{{ username }}
            </p>
            <p>
              <span class="text-start">Account type:&nbsp;</span>{{ account_type }}
            </p>
          </div>
        </div>
        <div class="overview__top__bottom my-5">
          {% comment %}send and receive{% endcomment %}
          <div class="d-flex justify-content-evenly">
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#sendModal">Send</button>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#requestModal">Request</button>
          </div>
          <div></div>
        </div>
      </div>
      <div class="overview__bottom w-75 mx-auto">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>Date</th>
              <th>User</th>
              <th>Transaction type</th>
              <th>Amount</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {% for transaction in transactions|slice:':8' %}
              <tr>
                <td>{{ transaction.created_at|date }}</td>
                <td>
                  {% if transaction.trxn_from.wallet.user.user_name %}
                    {{ transaction.trxn_from.wallet.user.user_name|capfirst }}
                  {% else %}
                    {{ transaction.wallet.user.user_name|capfirst }}
                  {% endif %}
                </td>
                <td>{{ transaction.trxn_type|capfirst }}</td>
                <td>{{ transaction.amount|to_value:request.user|floatformat:2|intcomma }}</td>
                <td>{{ transaction.status|upper }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  {% comment %}modals{% endcomment %}
  {% comment %}send modal{% endcomment %}
  <div class="modal fade" id="sendModal" tabindex="-1" aria-labelledby="sendModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="sendModalLabel">Send Funds</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          {% crispy send_form %}
        </div>
      </div>
    </div>
  </div>
  {% comment %}end send modal{% endcomment %}
  {% comment %}request modal{% endcomment %}
  <div class="modal fade" id="requestModal" tabindex="-1" aria-labelledby="requestModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="requestModalLabel">Request Funds</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          {% crispy request_form %}
        </div>
      </div>
    </div>
  </div>
  {% comment %}end request modal{% endcomment %}
  {% comment %}end modals{% endcomment %}
{% endblock %}

webapps2024/templates/user/transactions.html
{% extends './base.html' %}
{% load humanize %}
{% load custom_filters %}
{% block title %}
  <title>Transactions History</title>
{% endblock %}

{% block submain %}
  <main class="container">
    <h3 class="text-center">Transactions</h3>
    <table class="table table-striped table-hover my-5">
      <thead>
        <tr>
          <th>Date</th>
          <th>User</th>
          <th>Class</th>
          <th>Amount</th>
          <th>Type</th>
          <th>Balance</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for transaction in object_list %}
          <tr>
            <td>{{ transaction.created_at|date }}</td>
            <td>
              {% if transaction.trxn_from.wallet.user.user_name %}
                {{ transaction.trxn_from.wallet.user.user_name|capfirst }}
              {% else %}
                {{ transaction.wallet.user.user_name|capfirst }}
              {% endif %}
            </td>
            <td>{{ transaction.trxn_class|capfirst }}</td>
            <td>
              <span class="text-sm-center">
                {% if transaction.trxn_class == 'debit' %}
                  -
                {% else %}
                  +
                {% endif %}{{ transaction.amount|to_value:request.user|floatformat:2|intcomma }}
              </span>
            </td>
            <td>{{ transaction.trxn_type|upper }}</td>
            <td>
              {% if transaction.new_balance %}
                {{ transaction.new_balance|to_value:request.user|to_value:request.user|floatformat:2|intcomma }}
              {% else %}
                0
              {% endif %}
            </td>
            <td>{{ transaction.status|capfirst }}</td>
            <td>
              {% if transaction.trxn_type == 'transfer' and transaction.status == 'pending' %}
                <div>
                  <a href="{% url 'payapp:approve-transaction' pk=transaction.pk %}"><span class="btn btn-primary btn-sm">approve</span></a>
                  <a href="{% url 'payapp:decline-transaction' pk=transaction.pk %}"><span class="btn btn-danger btn-sm">decline</span></a>
                </div>
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <nav aria-label="Page navigation">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page=1" aria-label="First"><span aria-hidden="true">&laquo;&laquo;</span></a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
          </li>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
          <li class="page-item {% if num == page_obj.number %}{% endif %}">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
          </li>
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last"><span aria-hidden="true">&raquo;&raquo;</span></a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </main>
{% endblock %}